name: get and check proxy then push to release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9,21 * * *"
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  get_proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Getting proxies
        run: |
          python3 proxyScraper.py -p https,http -o output.txt

      - name: Check HTTP proxies
        run: |
          python3 proxyChecker.py -t 20 -s google.com -l output.txt -o output-tested.txt

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::Auto_ProxyList_$(date +'%Y.%m.%d')"

      - name: Release ProxyList
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            output.txt
            output-tested.txt
